steps:
  - id: BuildImage
    name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA
      - -t
      - gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest
      - --cache-from
      - gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest
      - .

  - id: PushImage
    name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/$PROJECT_ID/$_IMAGE_NAME

  - id: RunIntegrationTestAndDeploy
    name: "gcr.io/fersonality-1/acm-deploy"
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'REPO_NAME=$REPO_NAME'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'SHORT_SHA=$SHORT_SHA'
      - 'TAG_NAME=$TAG_NAME'
      - 'DEPLOY_IMAGE_NAME=$_IMAGE_NAME'
      - 'DEPLOY_NAMESPACE=$_DEPLOY_NAMESPACE'
      - 'DEPLOY_MANIFESTS_NAME=$_DEPLOY_MANIFESTS'

timeout: 600s
substitutions:
  _IMAGE_NAME: 'jaeger-gcp-proxy'
  _DEPLOY_NAMESPACE: 'monitoring'
  _DEPLOY_MANIFESTS: 'jaeger-gcp-proxy.yaml'
